### ISSUE TITLE
Unable to download dataset using given script

### ISSUE THREAD

**Issue by sawsa307** [zhou13/shapeunity#1]
As titled. I followed steps in README and ran specified scripts, but it seems like the command of downloading SU3.zip doesn't work. Is it possible to update the script/command? Thank you!

**Comment by zhou13** [comment]
Could you be more specific what is the problem? Does manually downloading from https://drive.google.com/file/d/1-TABJjT4-_yzE-iRD-n_yIJ9Kwzzkm7X work for you?

**Comment by sawsa307** [comment]
Yes downloading directly from Google Drive works for me, but I’m not able to download using the gdrive-download.sh script with the given file id.

**Comment by zhou13** [comment]
This is likely because Google is limiting the number of files that can be downloaded per day. The script works for me right now. I will close this issue and add a warning in the README.
