### ISSUE TITLE
Request for Updating pretrained_checkpoint.pth File Link

### ISSUE THREAD

**Issue by qszax** [zhou13/shapeunity#12]
First of all, thank you for sharing this amazing project. I've been exploring and learning a lot from it.

However, I encountered an issue with the link provided for the `pretrained_checkpoint.pth` file. It seems that the link is currently expired or no longer accessible. I would greatly appreciate it if you could update the link or provide an alternative way to access the `.pth` file.

Thank you!

**Comment by zhou13** [comment]
Sorry, the university limits the access to my Google Drive. I will re-upload it.

**Comment by zhou13** [comment]
This should have been fixed in 7d74d7c.
