### ISSUE TITLE
Sky Texture File in render_building.py

### ISSUE THREAD

**Issue by ljingyi** [zhou13/shapeunity#14]
First of all, I would like to express my sincere appreciation for your excellent work—it’s truly impressive. I am currently working with the data processing in the Blender script render_building.py, but  I seem to be having difficulty locating the sky texture file and would greatly appreciate it if you could share it with me. Thank you very much for your help!

**Comment by zhou13** [comment]
I haven't worked on this project for many years so I probably do not know the details. However, I think the .blend file should contain everything you need. Although I am not 100% sure, the sky texture should be embeded in the blender file.

**Comment by ljingyi** [comment]
Thank you for taking the time to respond to my message promptly.
