### ISSUE TITLE
Landmark 3D Wireframe Dataset

### ISSUE THREAD

**Issue by Luo1Cheng** [zhou13/shapeunity#2]
Hello, Zhou,  thanks for your excellent work. I am now trying to reconstruct 3D wireframe from real-world images and therefore I think L3D dataset will be helpful. Would you please plan to release the L3D dataset?

**Comment by zhou13** [comment]
Thanks for interesting in our datasets. I will try to release the L3D dataset after my recent deadlines.

**Comment by zhou13** [comment]
For the reference, the L3D dataset is at https://huggingface.co/yichaozhou/wireframe3d/tree/main/Data/MegaWireframe.
