### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Blame4** [zhou13/shapeunity#3]
Any clue that I got Segmentation fault (coredumped) when excuting
`python vectorize_u3d.py logs/pretrained-wireframe/npz/003576000 --vpdir logs/pretrained-vanishing-points/npz/000096000 57`
output:
`K: 2.6102218630949925
[[ 2.6102219  0.         0.         0.       ]
 [ 0.         2.6102219  0.         0.       ]
 [ 0.         0.         0.        -1.       ]
 [ 0.         0.         1.         0.       ]]
Segmentation fault (core dumped)
`

**Comment by zhou13** [comment]
Without extra information, it is hard to determine the cause. I suspect the problem is on the OpenGL/vispy side. If you are able to do some debugging, you can try to find the line number of the crash point.

**Comment by Blame4** [comment]
```
vps = vanish_point_refine(np.array(junctions), np.array(lines), 
# vps = vanish_point_clustering2(np.array(junctions), lines)
K = estimate_intrinsic_from_vp(vps[0][0], vps[1][0], vps[2][0])[0]
invK = LA.inv(K)
print("K:", 1 / invK[0, 0])
depth = lifting_from_vp(vps, invK, junctions, -juncdepth, junctypes, lines)
vertices, projection_matrix = to_world(junctions, depth, lines, K)
#show_wireframe(
#    f"{npzdir}/wireframe/{index:06}", vertices, lines, projection_matrix
#)
```

I saw the picture after I comment the last 3 lines in vectorize_u3d.py. 13 pictures show up one after I close another.
I will try to debug deeper

**Comment by Blame4** [comment]
It stoped here
` 85  def __init__(self, prefix, vertices, lines, proj_matrix, view_matrix):
 ->86      app.Canvas.__init__(self, config=dict(samples=8), size=(1024, 1024))`

in wireframe>viewer.py>Cavas>__init__

and no more message

**Comment by Blame4** [comment]
Ok, my fault.OpenGL is not installed well.
