### ISSUE TITLE
Installing dependencies

### ISSUE THREAD

**Issue by Brakebein** [zhou13/shapeunity#9]
Hi, thanks for the great work.

I want to test your code, however, I'm struggling to run it. I followed your notes on installation and downloaded the pre-trained models. I'm trying to execute the following command as said in the readme:

    python vectorize_u3d.py logs/pretrained-wireframe/npz/003576000 --vpdir logs/pretrained-vanishing-points/npz/000096000 57

First, I needed to figure out that I have to use python=3.7 instead of python=3.9 to resolve dependency conflicts during install.

After installation seemed fine, I'm now getting following error: 

```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "vectorize_u3d.py", line 39, in <module>
    from wireframe.optimize import (
  File "/home/brakebein/PycharmProjects/shapeunity/wireframe/optimize.py", line 5, in <module>
    import cvxpy as cvx
```

Wenn I decrease numpy version to `1.14`, I get another error:

```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "vectorize_u3d.py", line 39, in <module>
    from wireframe.optimize import (
  File "/home/brakebein/PycharmProjects/shapeunity/wireframe/optimize.py", line 5, in <module>
    import cvxpy as cvx
```

And during install I already got following message:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mkl-fft 1.2.0 requires numpy>=1.16, but you have numpy 1.14.6 which is incompatible.
cvxpy 1.1.17 requires numpy>=1.15, but you have numpy 1.14.6 which is incompatible.
```

However, increasing the numpy version to 1.16 and above throws the RuntimeError as said above.

Despite of consulting Google, stackoverflow, etc., I could not resolve this issue. So, my question is: Which dependency versions are required to successfully run your code?

**Comment by zhou13** [comment]
It is clear that your numpy version is too old according to the first error. You should upgrade it instead of downgrade it.

**Comment by Brakebein** [comment]
Thanks. I tested each version now, and with numpy `1.20` ad `1.21` it seens to work. I was pretty sure, I tested those versions before.

Now, I'm still struggling to download this SU3 dataset. It seems like the daily download limit has always been reached (I tested it the last 3 days). Or how can I test my own images with the pre-trained model?

**Comment by zhou13** [comment]
I have no problem downloading it manually with an Incognito tab.

**Comment by Brakebein** [comment]
For some strange reason, I wasn't able to download the dataset on Ubuntu with Firefox/Chrome (always saying that the maximum downloads per day was exceeded) or with your download script. I have now tested it on my Windows machine and the download worked without any problems.
